# Generated by Django 5.2.5 on 2025-09-16 03:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ball', 'Ball'), ('jersey', 'Jersey'), ('keychains', 'Keychains'), ('shoe', 'Shoe')], default='none', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
