# Generated by Django 5.2.5 on 2025-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_shop_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ball', 'Ball'), ('jersey', 'Jersey'), ('keychains', 'Keychains'), ('shoe', 'Shoe')], default='none', max_length=20),
        ),
    ]
